name: Java

on:
  pull_request:
    paths:
      - "**/*.java"
      - "**/*.gradle"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare-environment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

  detect-modified-files:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '**/*.java'

  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "temurin"

    - name: Compile modified Java file/s
      run: ./gradlew compileStarter --continue
      working-directory: exercises

    - name: Run all the tests corresponding to the modified exercise/s
      # run: ./gradlew test   # compileTestJava 
      run: ./gradlew :concept:lasagna:test   # This works!!
      working-directory: exercises

    - name: Lint modified Java files using Checkstyle
      run: ./gradlew check --exclude-task test --continue
      working-directory: exercises
   
    #    name: Compile modified Java files
    #    needs: detect-modified-files
    #    if: ${{ needs.detect-modified-files.outputs.src == 'true' }}
    #    runs-on: ubuntu-22.04
    #    steps:
    #      - uses: actions/checkout@v4
    #      - name: Check if the tests compile cleanly with starter sources
    #        run: ./gradlew compileStarterTestJava --continue
    #        working-directory: exercises

  lint:
    name: Lint modified Java files using Checkstyle - not working
    needs: detect-modified-files
    if: ${{ needs.detect-modified-files.outputs.src == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Lint modified Java files
        run: ./gradlew check --exclude-task test --continue
        working-directory: exercises

  test:
    name: Test all exercises using java-test-runner
    needs: detect-modified-files
    if: ${{ needs.detect-modified-files.outputs.src == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/checkout@v4
      - name: Test the modified exercise/s using java-test-runner
        run: bin/test-with-test-runner

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: exercises/**/build/results.json
        if: failure()
        # Artifacts are retained for 90 days by default

