name: Java

on:
  pull_request:
    paths:
      - "**/*.java"
      - "**/*.gradle"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare-environment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

  detect-modified-files:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '**/*.java'
      #      - name: Check if modified tests compile cleanly with starter sources
        # if: steps.changes.outputs.java == 'true'
        # working-directory: exercises
        # run: | 
        #  for file in ${{ steps.changes.outputs.java_files }}; do
            # Extract the exercise name from the file path
        #    exercise=$(echo "$file" | sed -E 's/exercises\/(.*)\/.*\.java/\1/')
            # Compile, check and run tests for the modified exercise
        #    ./gradlew ":${exercise}:compileStarterTestJava" --continue
        #    ./gradlew ":${exercise}:check" --exclude-task test --continue
        #    ./gradlew ":${exercise}:test"
        #  done

  compile:
    name: Compile modified Java files
    needs: detect-modified-files
    if: ${{ needs.detect-modified-files.outputs.src == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/checkout@v4
      # - name: Check if the test compile cleanly with starter sources
        run: ./gradlew compileStarterTestJava --continue
        working-directory: exercises

  lint:
    name: Lint modified Java files using Checkstyle
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/checkout@v4
      - name: Lint modified Java files
        if: steps.changes.outputs.java == 'true'
        working-directory: exercises
      ##- name: Set up JDK 1.17
      ##  uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
      ##  with:
      ##      java-version: 17
      ##      distribution: "temurin"
        run: |
          for file in ${{ steps.changes.outputs.java_files }}; do
            exercise=$(echo "$file" | sed -E 's/exercises\/(.*)\/.*\.java/\1/')
            ./gradlew ":${exercise}:check" --exclude-task test --continue
          done 

  test:
    name: Test all exercises using java-test-runner
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/checkout@v4
      - name: Test the modified exercise/s using java-test-runner
        if: steps.changes.outputs.java == 'true'
        run: bin/test-with-test-runner
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: exercises/**/build/results.json
        if: failure()
        # Artifacts are retained for 90 days by default

